name: Hartania-Plugin
author: xam4lor
version: 1.0
main: fr.hartania.xam4lor.main.MainClass
commands:
   ht:
      description: Commande du plugin hartania de base
      usage: /ht <giveItems>
   fly:
      description: Commande pour voler
      usage: /fly <1/0/on/off>
   msg:
      description: Commande pour envoyer des messages privés
      usage: /msg <pseudo> <message>
   m:
      description: Commande pour envoyer des messages privés
      usage: /m <pseudo> <message>
   grade:
      description: Commande pour modifier les grades des joueurs
      usage: /grade <pseudo> <modo/admin/joueur>
   global:
      description: Commande pour faire un message global (comme venant du serveur)
      usage: /global <message>
   actus:
      description: Commande pour afficher les mises à jour et modifications et pour en ajouter
      usage: /actus <add/list>
   mute:
      description: Commande pour muter un player
      usage: /mute <player>
   unmute:
      description: Commande pour unmute un player
      usage: /unmute <player>