name: Hartania-Plugin
author: xam4lor
version: 1.0
main: fr.hartania.xam4lor.main.MainClass
commands:
   ht:
      description: Commande du plugin hartania de base
      usage: /ht <giveItems>
   fly:
      description: Commande pour voler
      usage: /fly <1/0/on/off>
   msg:
      description: Commande pour envoyer des messages privés
      usage: /msg <pseudo> <message>
   m:
      description: Commande pour envoyer des messages privés
      usage: /m <pseudo> <message>
   grade:
      description: Commande pour modifier les grades des joueurs
      usage: /grade <pseudo> <modo/admin/joueur>
   global:
      description: Commande pour faire un message global (comme venant du serveur)
      usage: /global <message>
   actus:
      description: Commande pour afficher les mises à jour et modifications et pour en ajouter
      usage: /actus <add/list>
   mute:
      description: Commande pour muter un player
      usage: /mute <player>
   unmute:
      description: Commande pour unmute un player
      usage: /unmute <player>
   money:
      description: Commande pour voir la money d'un joueur
      usage: /money <player>
   lookup:
      description: Commande pour voir le status d'un joueur
      usage: /lookup <player>
   sound-msg:
      description: Commande pour voir le status d'un joueur
      usage: /sound-msg <1/0/on/off>
   mail:
      description: Commande pour envoyer un mail à un joueur
      usage: /mail <player> <message>
   clear-chat:
      description: Commande pour clear son chat
      usage: /clear-chat
   return:
      description: Commande pour retourner au spawn lors d'une mort dans un mini-jeu
      usage: /return